spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurante?useTimezone=true&serverTimezone=UTC
    username: root
    password: desenv
  jpa:
    show-sql: true
    open-in-view: true
    database: mysql
    hibernate:
      ddl-auto: update
